---

# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: Run Docker {{ docker_ce_version }} Install Script
  script: "files/get-docker.sh {{ docker_ce_version }}"
  when: docker_there.stat.exists == False
  register: docker_installed
  become: yes

- name: Lock docker version to {{ docker_ce_version}}
  command: /usr/bin/apt-mark hold docker-ce
  when: docker_installed.changed
  become: yes

- name: Install k8s {{ kubernetes_package_version }} Y'all
  apt:
    name: "{{ item }}={{ kubernetes_package_version }}"
    state: present
    force: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: yes 