---

- name: gpu mem check
  shell: cat /boot/config.txt | grep gpu_mem
  changed_when: false
  register: gpu_mem_check

- name: reduce gpu memory
  lineinfile:
    path: /boot/config.txt
    line: gpu_mem=16
  register: gpu_mem
  when: gpu_mem_check.stdout == ""

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: Disable Swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True